### ISSUE TITLE
Tagged version of Docker images are using snapshots of Backend and UI

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-standalone#24]
for isntance with `docker run --rm -p 8080:8081 --name kaoto kaotoio/standalone:0.7.3`

it is logging:

```
2023-03-21 10:22:34,744 INFO  [io.quarkus] (main) kaoto-backend 0.7.4-SNAPSHOT native (powered by Quarkus 2.15.2.Final) started in 15.175s. Listening on: http://0.0.0.0:8081
```

**Comment by Delawen** [comment]
Do native and JAR standalone have the same issue?

**Comment by Delawen** [comment]
Originally the (very bad) idea was to tag versions on this repo too and use that to extract the tag to use for frontend and backend.

But the nightly job just takes main as the tag.

Improving this...

**Comment by Delawen** [comment]
There is this other job that you can manually choose which versions to use 
![image](https://user-images.githubusercontent.com/726590/227152343-5afcffb3-ad51-4693-b467-ba1a94a3aa8b.png)

**Comment by Delawen** [comment]
Incidentally, decided to add an endpoint to check the running backend version https://github.com/KaotoIO/kaoto-backend/pull/566

**Comment by Delawen** [comment]
Tried to build 0.7.4 but it also shows the dev version:

`docker run --rm -p 8080:8081 --name kaoto kaotoio/standalone:0.7.4`

`2023-03-23 09:45:07,622 INFO  [io.quarkus] (main) kaoto-backend 0.7.5-SNAPSHOT native (powered by Quarkus 2.15.2.Final) started in 0.518s. Listening on: http://0.0.0.0:8081`
